### ISSUE TITLE
Incompatibility with ZF 2.4

### ISSUE THREAD

**Issue by gabrielsomoza** [zfcampus/zf-rest#69]
[This change](https://github.com/zfcampus/zf-rest/commit/cc7ddfd31539111e58ee33fc9c9e56acef9e4641#commitcomment-10625491) forced me to require this dependency of this package directly in my `composer.json` file instead of letting Composer figure out the best version. 

Looks like Composer was resolving to Zend Framework 2.4 and therefore was choosing the previous version of this package (1.0.3), which is the one with a compatibility issue with ZF 2.4. It couldn't choose version `1.0.4` because its incompatible with ZF 2.4. So kind of a catch-22, unless I'm missing something?

Like I said, the only way I could fix this is by explicitly requiring this package version `1.0.4`, which made Composer uninstall ZF 2.4 and install version 2.3.7.

I didn't test this, but I suspect that a clean install of Apigility through composer will duplicate the issue I had at the time of this writing.

**Comment by weierophinney** [comment]
The change you reference was made because ZF 2.4 deprecates the EventManager's `triggerUntil` method. You could get around it by changing your `error_reporting` to add `^E_DEPRECATED ^E_USER_DEPRECATED`, which removes the problem.

That said, we pinned current master of zf-rest to `~2.3.0` and tagged v1.0.4, because there's a bigger BC break in ZF 2.4 which makes current master incompatible: `Zend\Mvc\Controller\AbstractRestfulController::deleteList()` now has a **required** `$data` argument. In zf-rest, on current master, it's an **optional** argument, which means we simply *cannot* update to 2.4 yet, and have it compatible with **both** ZF 2.3 **and** ZF 2.4 simultaneously.

#64 updates zf-rest to work for 2.4, and this change will be released with v1.1 early next week.

**Comment by gabrielsomoza** [comment]
We'll just wait until next week in that case, thanks!
