### ISSUE TITLE
`collection_query_whitelist` default behaviour?

### ISSUE THREAD

**Issue by Wilt** [zfcampus/zf-rest#73]
*Not sure if this is an issue or a question or maybe a documentation enhancement request.*

I just found out that if I don't set any [`collection_query_whitelist`](https://github.com/zfcampus/zf-rest#sub-key-collection_query_whitelist-optional) in my controller config that all parameters are allowed. I somehow assumed the opposite, that if no parameter is set all parameters will be filtered from `$data`.

So I expected setting no whitelist would result in the same behaviour as `collection_query_whitelist` => array()

Is this the correct default behaviour?
If yes, may I suggest adding a comment to the controller config [documentation here](https://github.com/zfcampus/zf-rest#sub-key-collection_query_whitelist-optional) that omitting the parameter will result in white listing all parameters.

**Comment by weierophinney** [comment]
That's not the correct behavior; `$data` should be empty if the whitelist is empty. I'll investigate.

**Comment by weierophinney** [comment]
@Wilt I cannot confirm this. I created my `fetchAll()` method in a code-connected REST service as follows:

```php
public function fetchAll($params = array())
{
    return array(
        array(
            'id' => 1,
            'params' => $params,
        )
    );
}
```

And then sent a request to `/foo?bar=baz&baz=bat`. The result had an empty `params` object for that entity.

**Comment by Wilt** [comment]
I am not sure since it was some time ago I asked this question but I tried once more and maybe I didn't explain it correctly. Now I noticed the following:

In my zf-rest `ResourceListener` instance I use the following method to get the query params from the resource event:

$queryParams = $event->getQueryParams();

If I set no `collection_query_whitelist` key in my controller config array this method returns me all query params that qere passed in the request. If I set an empty array as `collection_query_whitelist` then the method returns nothing (an empty `Zend\Stdlib\Parameters` object).

**Comment by Wilt** [comment]
@weierophinney I hope you still get notified by this since you closed the issue...

**Comment by Wilt** [comment]
Any updates on this bug? 
Seems to be a security breach if you ask me. Unexpected data can add up on sensitive places in the application.

**Comment by weierophinney** [comment]
The whitelist was originally developed to filter what query parameters made their way into a resource. Before that, they were always present. With the whitelist, we could determine exactly which ones could be passed along, and indicate none should be available by passing an empty array.

The original behavior - allowing all parameters - exists essentially to allow users to use whatever query parameters they want. This can be important in development, where you may be trying different parameters and naming conventions. Ideally, once you know exactly what you need, you should create a collection_query_whitelist to lock down what is passed to the resource.

I'm failing to see how this is a potential security breach, however. Developers know the exact source, and should be filtering those parameters accordingly, and should be careful to track the origin of the parameters when merging with any other user input.

If you feel I'm missing the security implication, please use our security reporting procedures to fully explain the vector, instead of doing so in a public channel.
