### ISSUE TITLE
Batch POST response does not include  collection name

### ISSUE THREAD

**Issue by metanav** [zfcampus/zf-rest#79]
When I send a batch POST request on an "article" resource,  the response misses the collection name.

Batch POST response :

```json
 {"_embedded" : [{"id": 1, "name": "test1"}, {"id": 2, "name": "test2"}] }
```

But the batch PATCH request on the same resource behaves normally.

Batch PATCH response :

```json
{"_embedded" : { "article" : [{"id": 1, "name": "test1"}, {"id": 2, "name": "test2"}] }}
```

**Comment by weierophinney** [comment]
This is because `RestController` and `Resource` are not really setup well to handle `POST` requests with batched entities. The default use case is to handle creation of a single entity only, as we have no way of auto-recognizing if the payload represents a single entity or multiple entities.

Right now, the only way to do this properly is to handle it in your `Resource` class, and have the `create()` method return a fully populated `Response` instance that contains the rendered collection.

I'm going to create a patch now that will simplify this somewhat, and allow you to return `ZF\Hal\Entity` and/or `ZF\Hal\Collection` instances from the `Resource::create()` method; if it detects those, then it will inject the `self` relational link and merrily continue forward. This doesn't fully answer the problem you're seeing, but *will* allow you to create the `ZF\Hal\Collection` instance manually in your `Resource` and return it, ensuring it's rendered correctly:

```php
public function create($data)
{
    // 1. somehow get your data set
    // 2. possibly pass it to a paginator/collection object
    // 3. create your ZF\Hal\Collection and return it:
    return new \ZF\Hal\Collection($dataSetOrPaginator);
}
```

(My plan is to implement it such that the `RestController` injects it with the collection name and routing information for you, so you don't need to track that in your `Resource`.)

**Comment by weierophinney** [comment]
@metanav With the solution proposed in #84, you'll be able to return a `ZF\Hal\Collection` from your resource's `create()` method now. The controller will populate it with the collection name, routing information, and pagination details, ensuring it's rendered correctly.

What this will mean is that you cannot just return a paginator or array or traversable back from the `create()` method following a batch operation; you'll need to return a `ZF\Hal\Collection`. This was the only way I could figure out how to make `RestController::create()` properly handle both entity and collection operations.
